version: '3.9'

services:
  node:
    build: ./node
    container_name: myportfolio
    volumes:
      - ./node/app:/usr/src/app:cached
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "3000:3000"